services:
  # PostgreSQL Database
  db:
    image: postgres:16
    container_name: django_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hummer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - flask-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_test
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - flask-network

  # Django Backend
  backend:
    build:
      context: ./backend
    container_name: django_backend
    restart: unless-stopped
    environment:
      DEBUG: ${DEBUG:-False}
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-here}
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-referal_db}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-localhost 127.0.0.1 [::1]}
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 myproject.wsgi:application"

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
    container_name: nextjs_frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://nginx/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    expose:
      - "3000"
    networks:
      - app-network
    depends_on:
      - backend
    command: npm start

  # Nginx Reverse Proxy
  nginx:
    build:
      context: ./nginx
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - app-network
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  pgadmin_data:
  static_volume:
  media_volume:

networks:
  app-network:
    driver: bridge